<?php

use Illuminate\Database\Seeder;

use App\Models\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            "Accountants",
            "Advertising/Public Relations",
            "Aerospace, Defense Contractors",
            "Agribusiness",
            "Agricultural Services & Products",
            "Agriculture",
            "Air Transport",
            "Air Transport Unions",
            "Airlines",
            "Alcoholic Beverages",
            "Alternative Energy Production & Services",
            "Architectural Services",
            "Attorneys/Law Firms",
            "Auto Dealers",
            "Auto Dealers, Japanese",
            "Auto Manufacturers",
            "Automotive",
            "Banking, Mortgage",
            "Banks, Commercial",
            "Banks, Savings & Loans",
            "Bars & Restaurants",
            "Beer, Wine & Liquor",
            "Books, Magazines & Newspapers",
            "Broadcasters, Radio/TV",
            "Builders/General Contractors",
            "Builders/Residential",
            "Building Materials & Equipment",
            "Business Associations",
            "Business Services",
            "Cable & Satellite TV Production & Distribution",
            "Candidate Committees",
            "Candidate Committees, Democratic",
            "Candidate Committees, Republican",
            "Car Dealers",
            "Car Dealers, Imports",
            "Car Manufacturers",
            "Casinos / Gambling",
            "Cattle Ranchers/Livestock",
            "Chemical & Related Manufacturing",
            "Chiropractors",
            "Civil Servants/Public Officials",
            "Clergy & Religious Organizations",
            "Clothing Manufacturing",
            "Coal Mining",
            "Colleges, Universities & Schools",
            "Commercial Banks",
            "Commercial TV & Radio Stations",
            "Communications/Electronics",
            "Computer Software",
            "Conservative/Republican",
            "Construction",
            "Construction Services",
            "Construction Unions",
            "Credit Unions",
            "Crop Production & Basic Processing",
            "Cruise Lines",
            "Cruise Ships & Lines",
            "Dairy",
            "Defense",
            "Defense Aerospace",
            "Defense Electronics",
            "Defense/Foreign Policy Advocates",
            "Democratic Candidate",
            "Committees",
            "Democratic Leadership PACs",
            "Democratic/Liberal",
            "Dentists",
            "Doctors & Other Health Professionals",
            "Drug Manufacturers",
            "Education",
            "Electric Utilities",
            "Electronics Manufacturing & Equipment",
            "Electronics, Defense Contractors",
            "Energy & Natural Resources",
            "Entertainment Industry",
            "Environment",
            "Farm Bureaus",
            "Farming",
            "Finance / Credit Companies",
            "Finance, Insurance & Real Estate",
            "Fine Arts & Entertainment",
            "Food & Beverage",
            "Food Processing & Sales",
            "Food Products Manufacturing",
            "Food Stores",
            "For-profit Education",
            "Foreign & Defense Policy",
            "Forestry & Forest Products",
            "Foundations, Philanthropists & Non-Profits",
            "Funeral Services",
            "Gambling & Casinos",
            "Gambling, Indian Casinos",
            "Garbage Collection/Waste Management",
            "Gas & Oil",
            "General Contractors",
            "Guns & Ammunition",
            "Health",
            "Health Professionals",
            "Health Services/HMOs",
            "Hedge Funds",
            "HMOs & Health Care Services",
            "Home Builders",
            "Hospitals & Nursing Homes",
            "Hotels, Motels & Tourism",
            "Human Rights",
            "Insurance",
            "Internet",
            "Labor",
            "Lawyers / Law Firms",
            "Leadership PACs",
            "Liberal/Democratic",
            "Liquor, Wine & Beer",
            "Livestock",
            "Lodging / Tourism",
            "Logging, Timber & Paper",
            "Mills",
            "Manufacturing, Misc",
            "Marine Transport",
            "Meat processing & products",
            "Medical Supplies",
            "Mining",
            "Misc Business",
            "Misc Finance",
            "Misc Manufacturing & Distributing",
            "Miscellaneous Defense",
            "Miscellaneous Services",
            "Mortgage Bankers & Brokers",
            "Motion Picture Production & Distribution",
            "Music Production",
            "Natural Gas Pipelines",
            "Newspaper, Magazine & Book Publishing",
            "Non-profits, Foundations & Philanthropists",
            "Nurses",
            "Nursing Homes/Hospitals",
            "Nutritional & Dietary Supplements",
            "Oil & Gas",
            "Organic Products",
            "Other",
            "Payday Lenders",
            "Pharmaceutical Manufacturing",
            "Pharmaceuticals / Health",
            "Products",
            "Phone Companies",
            "Physicians & Other Health",
            "Professionals",
            "Poultry & Eggs",
            "Power Utilities",
            "Printing & Publishing",
            "Private Equity & Investment Firms",
            "Professional Sports, Sports Arenas & Related Equipment & Services",
            "Progressive/Democratic",
            "Public Employees",
            "Publishing & Printing",
            "Radio/TV Stations",
            "Railroads",
            "Real Estate",
            "Record Companies/Singers",
            "Recorded Music & Music Production",
            "Recreation / Live Entertainment",
            "Religious Organizations/Clergy",
            "Republican Candidate Committees",
            "Republican Leadership PACs",
            "Republican/Conservative",
            "Residential Construction",
            "Restaurants & Drinking Establishments",
            "Retail Sales",
            "Retired",
            "Savings & Loans",
            "Schools/Education",
            "Sea Transport",
            "Securities & Investment",
            "Special Trade Contractors",
            "Sports, Professional",
            "Steel Production",
            "Stock Brokers/Investment Industry",
            "Student Loan Companies",
            "Sugar Cane & Sugar Beets",
            "Teachers/Education",
            "Telecom Services & Equipment",
            "Telephone Utilities",
            "Textiles",
            "Timber, Logging & Paper Mills",
            "Tobacco",
            "Transportation",
            "Transportation Unions",
            "Trash Collection/Waste Management",
            "Trucking",
            "TV / Movies / Music",
            "TV Production",
            "Universities, Colleges & Schools",
            "Vegetables & Fruits",
            "Venture Capital",
            "Waste Management",
            "Wine, Beer & Liquor",
            "Women's Issues",
        ];

         foreach ($categories as $category) {
            try {
                $found = Category::where([
                    'slug' => str_slug($category)
                ])->first();

                if (!is_null($found)) continue;

                Category::create([
                    'name' => $category,
                    'slug' => str_slug($category)
                ]);

            } catch (PDOException $e) {
                
            }
        }
    }
}
